// The shared routing contract: shared/routing-decision-vectors.json run against
//   (1) the canonical ES module, shared/decide-route.js, and
//   (2) the classic-script bundle the extension actually ships,
//       content/model-routing.js (generated by scripts/gen-shared-routing.mjs).
//
// The vectors are the spec the desktop enforcer's C# port must ALSO pass, so a
// case changed here is a behaviour change for every routing engine — bump the
// vectors deliberately, never to make a red test green.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..', '..');
const SHARED = path.join(root, 'shared');

const catalog = JSON.parse(readFileSync(path.join(SHARED, 'model-catalog.json'), 'utf8'));
const vectors = JSON.parse(readFileSync(path.join(SHARED, 'routing-decision-vectors.json'), 'utf8'));
const esm = await import(pathToFileURL(path.join(SHARED, 'decide-route.js')).href);
const gen = await import(pathToFileURL(path.join(root, 'scripts', 'gen-shared-routing.mjs')).href);

const bundleSrc = readFileSync(path.join(here, '..', 'content', 'model-routing.js'), 'utf8');
function loadBundle() {
  const win = {};
  // eslint-disable-next-line no-new-func
  new Function('window', bundleSrc)(win);
  return win.__cfaiRouting;
}
const bundle = loadBundle();

const policyOf = (p) => (typeof p === 'string' ? vectors.policies[p] : p);

function check(label, out, expect, id) {
  for (const [k, v] of Object.entries(expect)) {
    assert.deepEqual(out[k], v, `[${label}] ${id}: ${k} expected ${JSON.stringify(v)} got ${JSON.stringify(out[k])}\n  full: ${JSON.stringify(out)}`);
  }
}

test('the corpus is big enough to be a contract (>= 40 decision cases)', () => {
  assert.ok(vectors.cases.length >= 40, `only ${vectors.cases.length} cases`);
  const ids = vectors.cases.map((c) => c.id);
  assert.equal(new Set(ids).size, ids.length, 'duplicate case ids');
  for (const c of vectors.cases) {
    if (typeof c.policy === 'string') assert.ok(c.policy in vectors.policies, `${c.id}: unknown policy ${c.policy}`);
  }
});

test('the corpus covers every result the contract can produce', () => {
  const seen = new Set(vectors.cases.map((c) => c.expect.result));
  for (const r of ['routed', 'suggested', 'observed', 'noop', 'unsupported', 'disabled', 'user_override']) {
    assert.ok(seen.has(r), `no vector produces result '${r}'`);
  }
});

test('every vector passes against shared/decide-route.js (canonical ESM)', () => {
  for (const c of vectors.cases) {
    check('esm', esm.decideRoute(c.ctx, policyOf(c.policy), catalog), c.expect, c.id);
  }
});

test('every vector passes against the shipped extension bundle (content/model-routing.js)', () => {
  for (const c of vectors.cases) {
    check('bundle', bundle.decideRoute(c.ctx, policyOf(c.policy)), c.expect, c.id);
  }
});

test('label detection vectors pass in both builds', () => {
  for (const v of vectors.label_detection) {
    const policy = v.policy ? policyOf(v.policy) : null;
    const e1 = esm.resolveSurface(catalog, v.surface, v.host_or_app, policy, null);
    const e2 = bundle.resolveSurface(v.surface, v.host_or_app, policy, null);
    assert.ok(e1 && e2, `no surface for ${v.host_or_app}`);
    assert.equal(esm.detectTierFromLabel(e1, v.text), v.tier, `esm: ${JSON.stringify(v.text)} on ${v.host_or_app}`);
    assert.equal(bundle.detectTierFromLabel(e2, v.text), v.tier, `bundle: ${JSON.stringify(v.text)} on ${v.host_or_app}`);
  }
});

test('the checked-in bundle is exactly what the generator produces (no drift)', () => {
  const fresh = gen.buildBundle().replace(/\r\n/g, '\n');
  assert.equal(bundleSrc.replace(/\r\n/g, '\n'), fresh,
    'content/model-routing.js is stale — run `node scripts/gen-shared-routing.mjs`');
});

test('decideRoute is pure: same input, same output, input not mutated', () => {
  const c = vectors.cases.find((x) => x.id === 'rule-set-tier-with-builtin-low-effort');
  const policy = JSON.parse(JSON.stringify(policyOf(c.policy)));
  const before = JSON.stringify([c.ctx, policy]);
  const a = esm.decideRoute(c.ctx, policy, catalog);
  const b = esm.decideRoute(c.ctx, policy, catalog);
  assert.deepEqual(a, b);
  assert.equal(JSON.stringify([c.ctx, policy]), before, 'decideRoute mutated its input');
});

test('decideRoute never throws on garbage input and fails to a non-routing result', () => {
  for (const [ctx, policy] of [
    [null, null], [undefined, undefined], [{}, {}], [{ surface: 'browser' }, 'nonsense'],
    [{ surface: 'browser', host_or_app: 'claude.ai', current_tier: 'premium', complexity: 'simple' }, { rules: 'x' }],
    [{ surface: 'browser', host_or_app: 'claude.ai', current_tier: 7, complexity: 'simple' }, [null, 1, 'a']],
  ]) {
    const out = esm.decideRoute(ctx, policy, catalog);
    assert.ok(out && typeof out.result === 'string');
  }
  // A malformed rules list is ignored, not fatal: the built-in table still applies.
  const out = esm.decideRoute({ surface: 'browser', host_or_app: 'claude.ai', current_tier: 'premium', complexity: 'simple' },
    { rules: [null, 1, 'a', { action: null }] }, catalog);
  assert.equal(out.target_tier, 'economy');
});

test('the decision carries no prompt-derived field (privacy contract)', () => {
  const out = esm.decideRoute({
    surface: 'browser', host_or_app: 'claude.ai', provider: 'anthropic', current_tier: 'premium',
    complexity: 'simple', prompt: 'my SSN is 123-45-6789',
  }, null, catalog);
  assert.ok(!JSON.stringify(out).includes('123-45-6789'));
  assert.deepEqual(Object.keys(out).sort(), [
    'click_labels', 'effort', 'from_tier', 'mode', 'model', 'reason', 'result',
    'rule_id', 'rule_name', 'target_tier', 'to_label',
  ]);
});

test('catalog: every verified:true entry names its evidence; every tier has a click label', () => {
  for (const [kind, map] of [['hosts', catalog.hosts], ['apps', catalog.apps]]) {
    for (const [key, entry] of Object.entries(map)) {
      if (entry.alias_of) { assert.ok(map[entry.alias_of], `${kind}.${key} aliases a missing entry`); continue; }
      assert.ok(catalog.providers[entry.provider], `${kind}.${key}: unknown provider ${entry.provider}`);
      if (entry.verified) assert.ok(entry.evidence && entry.evidence.length > 20, `${kind}.${key} is verified with no evidence`);
      for (const t of ['economy', 'standard', 'premium']) {
        const te = entry.tiers[t];
        assert.ok(te && te.click_labels.length > 0, `${kind}.${key}.${t} has no click label`);
        assert.ok(te.button_label_patterns.length > 0, `${kind}.${key}.${t} has no read pattern`);
        if (te.verified) assert.ok(entry.verified, `${kind}.${key}.${t} verified on an unverified surface`);
      }
    }
  }
  for (const h of ['claude.ai', 'chatgpt.com', 'gemini.google.com', 'perplexity.ai', 'chat.mistral.ai', 'aistudio.google.com']) {
    assert.ok(catalog.hosts[h], `catalog missing host ${h}`);
  }
  for (const a of ['claude_desktop', 'chatgpt_desktop']) assert.ok(catalog.apps[a], `catalog missing app ${a}`);
  for (const p of ['anthropic', 'openai', 'google', 'perplexity', 'mistral']) {
    for (const t of ['economy', 'standard', 'premium']) {
      assert.ok(catalog.providers[p].tiers[t].api_ids.length > 0, `${p}.${t} has no api ids`);
    }
  }
});

test('catalog: every click label reads back as its own tier (no label points at another tier)', () => {
  for (const map of [catalog.hosts, catalog.apps]) {
    for (const [key, raw] of Object.entries(map)) {
      if (raw.alias_of) continue;
      const surface = map === catalog.hosts ? 'browser' : 'desktop_app';
      const entry = esm.resolveSurface(catalog, surface, key, null, null);
      for (const t of ['economy', 'standard', 'premium']) {
        for (const label of entry.tiers[t].click_labels) {
          assert.equal(esm.detectTierFromLabel(entry, label), t,
            `${key}: clicking '${label}' for ${t} would be read back as ${esm.detectTierFromLabel(entry, label)}`);
        }
      }
    }
  }
});

// The desktop agent's web arm used to carry its OWN hand-copied click labels
// (ai-processes.js modelPicker.tierLabels). claude.ai's went stale ('Sonnet 5'
// vs the live 'Sonnet 5.5') and every browser route the agent drove failed
// from_tier_not_confirmed (live 2026-10-06). They are now DERIVED from this
// catalog, so the agent's web arm, the desktop arm and this extension click the
// same strings.
const aiProcs = await import(pathToFileURL(path.join(root, 'agent', 'src', 'os_monitor', 'ai-processes.js')).href);
function agentTierLabels(id) {
  const s = aiProcs.WEB_SURFACES.find((x) => x.id === id);
  assert.ok(s && s.modelPicker && s.modelPicker.tierLabels, id + ' modelPicker tierLabels not found in ai-processes.js');
  return s.modelPicker.tierLabels;
}

test('Gemini labels: the agent web arm clicks the catalog labels (ai-processes.js gemini_web modelPicker)', () => {
  const m = agentTierLabels('gemini_web');
  const g = catalog.hosts['gemini.google.com'].tiers;
  assert.equal(g.premium.click_labels[0], m[3]);
  assert.equal(g.standard.click_labels[0], m[2]);
  assert.equal(g.economy.click_labels[0], m[1]);
  // The live-measured 2026-09-22 menu strings, unchanged.
  assert.deepEqual({ ...m }, { 3: '3.1 Pro', 2: '3.8 Flash', 1: '3.5 Flash-Lite' });
});

test('claude.ai labels: the agent web arm clicks the catalog labels (ai-processes.js claude_web modelPicker)', () => {
  const m = agentTierLabels('claude_web');
  const c = catalog.hosts['claude.ai'].tiers;
  assert.equal(c.premium.click_labels[0], m[3]);
  assert.equal(c.standard.click_labels[0], m[2]);
  assert.equal(c.economy.click_labels[0], m[1]);
  assert.equal(c.premium.click_labels[0], 'Opus 5.5');
  assert.equal(c.standard.click_labels[0], 'Sonnet 5.5');
  // The 2026-09-22 names stay in the catalog as fallbacks.
  assert.ok(c.premium.click_labels.includes('Opus 5'));
  assert.ok(c.standard.click_labels.includes('Sonnet 5'));
});
