export const SET_CF_USER = "SET_CF_USER";
export const SET_SAAS_CLOUD = "SET_SAAS_CLOUD";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_CLOUDS_LIST = "SET_CLOUDS_LIST";
export const SET_JOB_DETAILS = "SET_JOB_DETAILS";
export const SET_OAUTH_STATUS = "SET_OAUTH_STATUS";
export const SET_MAPPED_PAIRS = "SET_MAPPED_PAIRS";
export const SET_SESSION_TIME = "SET_SESSION_TIME";
export const RESET_APP_CONTEXT = "RESET_APP_CONTEXT";
export const SET_SOURCE_MAPPING = "SET_SOURCE_MAPPING";
export const SET_CSV_MAPPING_ID = "SET_CSV_MAPPING_ID";
export const RESET_MAPPING_PAIRS = "RESET_MAPPING_PAIRS";
export const RESET_SAAS_DATA = "RESET_SAAS_DATA";
export const SET_GROUPS_TEAMS_LIST = "SET_GROUPS_TEAMS_LIST";
export const SET_GROUPS_TEAMS_SUMMARY = "SET_GROUPS_TEAMS_SUMMARY";
export const SET_RESOURCE_APP_LIST = "SET_RESOURCE_APP_LIST";
export const SET_UPDATE_JOB_PARAMS = "SET_UPDATE_JOB_PARAMS";
export const SET_DESTINATION_MAPPING = "SET_DESTINATION_MAPPING";
export const SET_RESOURCE_APP_SUMMARY = "SET_RESOURCE_APP_SUMMARY";
export const SET_SELECTED_SOURCE_CLOUD = "SET_SELECTED_SOURCE_CLOUD";
export const SET_BILLING_SUMMARY = "SET_BILLING_SUMMARY";

export const SET_SIDEBAR_COLLAPSED = "SET_SIDEBAR_COLLAPSED";

// States for Message Migrations
export const SET_SELECTED_CHANNELS_MAPPING = "SET_SELECTED_CHANNELS_MAPPING";
export const SET_SELECTED_DMS_MAPPING = "SET_SELECTED_DMS_MAPPING";
export const SET_SELECTED_DESTINATION_CLOUD = "SET_SELECTED_DESTINATION_CLOUD";
