import { createContext } from "react";

export const GlobalContext = createContext({
  time: 0,
  user: {},
  userId: "",
  csvId: "",
  userEmail: "",
  authToken: "",
  jobDetails: {},
  oauthStatus: "",
  jobParams: "",
  mappingSource: [],
  mappingDestination: [],
  mappedPairs: [],
  cloudsList: [],
  sourceCloud: {},
  rolesList: [],
  saasCloud: {},
  billingSummary: {},
  channelsMappingsList: {
    public: [],
    export: [],
    private: [],
    exportIds: [],
    publicIds: [],
    privateIds: [],
  },
  dmsMappingsList: {
    dms: [],
    dmIds: [],
  },
  destinationCloud: {},
  groupsTeamsList: [],
  resourceAppsList: [],
  groupsTeamsSummary: {},
  resourceAppsSummary: {},
  sidebarCollapsed: false,
});
