#!/usr/bin/env node
// Top-level release script. Produces alpha artifacts in dist/<version>/:
//
//   dist/<version>/
//     agent-<platform>-<arch>/                  endpoint agent + native modules
//     dashboard/                                static build of the React app
//     browser-extension/                        zipped MV3 extension
//     server-bundle.zip                         server source + production deps
//     SHA256SUMS.txt                            hash manifest
//     RELEASE_NOTES.md                          autogenerated release notes
//
// Usage:
//   node scripts/release.mjs [version]
//   (default: pulls version from agent/package.json)

import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, copyFile, readFile, writeFile, rm, readdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join, basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';

const execAsync = promisify(exec);
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const agentDir   = join(root, 'agent');
const serverDir  = join(root, 'server');
const dashDir    = join(root, 'dashboard');
const extDir     = join(root, 'browser-extension');

const pkg = JSON.parse(await readFile(join(agentDir, 'package.json'), 'utf8'));
const version = process.argv[2] || pkg.version;
const distRoot = join(root, 'dist', version);

console.log(`Releasing ${version} → ${distRoot}\n`);
await rm(distRoot, { recursive: true, force: true });
await mkdir(distRoot, { recursive: true });

const steps = [
  { name: 'agent (host platform only)', fn: buildAgent },
  { name: 'dashboard',                  fn: buildDashboard },
  { name: 'browser extension zip',      fn: packExtension },
  { name: 'server bundle',              fn: packServer },
  { name: 'hashes',                     fn: writeHashes },
  { name: 'release notes',              fn: writeReleaseNotes },
];

for (const step of steps) {
  process.stdout.write(`• ${step.name}… `);
  try {
    await step.fn();
    console.log('done');
  } catch (err) {
    console.log('FAILED');
    console.error(err.message);
    process.exit(1);
  }
}

console.log(`\n✓ Release artifacts ready in ${distRoot}`);

// ---- step implementations ----

async function buildAgent() {
  await execAsync('npm run build', { cwd: agentDir, env: process.env });
  const buildDir = join(agentDir, 'build');
  const entries = await readdir(buildDir, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory() || !/^(win32|darwin|linux)-/.test(e.name)) continue;
    const src = join(buildDir, e.name);
    const dest = join(distRoot, `agent-${e.name}`);
    await copyDir(src, dest);
  }
}

async function buildDashboard() {
  await execAsync('npm run build', { cwd: dashDir });
  await copyDir(join(dashDir, 'dist'), join(distRoot, 'dashboard'));
}

async function packExtension() {
  // ZIP the browser-extension directory minus README and node_modules.
  const outZip = join(distRoot, 'browser-extension.zip');
  await zipDir(extDir, outZip, ['node_modules', '.DS_Store']);
}

async function packServer() {
  // Bundle src + package.json + migrations. Operators install deps in place.
  const outZip = join(distRoot, 'server-bundle.zip');
  await zipDir(serverDir, outZip, ['node_modules', 'data', 'dist']);
}

async function writeHashes() {
  const files = await walkFiles(distRoot);
  const lines = [];
  for (const f of files) {
    if (basename(f) === 'SHA256SUMS.txt') continue;
    const buf = await readFile(f);
    const h = createHash('sha256').update(buf).digest('hex');
    lines.push(`${h}  ${f.slice(distRoot.length + 1).replace(/\\/g, '/')}`);
  }
  await writeFile(join(distRoot, 'SHA256SUMS.txt'), lines.join('\n') + '\n');
}

async function writeReleaseNotes() {
  const date = new Date().toISOString().slice(0, 10);
  const body = `# CloudFuze AI Governance — ${version}

Released: ${date}

## What's in this release

- **Endpoint agent** for Windows / macOS / Linux (single binary + native SQLite binding).
- **Backend server** with JWT-based machine auth, SQLite for dev, Postgres adapter for prod.
- **React dashboard** with Overview, Machines, Tools, Agents & MCP, DLP, and Shadow AI views.
- **Browser extension** (MV3) for ChatGPT / Claude / Gemini / Perplexity / Copilot DLP.

## Detector pillars (Pillar 1: Discovery)

1. \`desktop_apps\` — installed AI apps + running AI processes
2. \`browser_history\` — AI service domain visits (Chrome / Edge / Firefox / Brave)
3. \`ide_extensions\` — VS Code / Cursor / JetBrains AI extensions
4. \`agent_configs\` — Claude Desktop / Claude Code / Cursor / Continue configs + deep MCP server inspection
5. \`api_keys\` — fingerprinted (never the raw key)
6. \`agent_projects\` — local folders matching AI SDK / framework signatures
7. \`running_agents\` — autonomous AI agents currently executing

## Pillar 2: Governance

- Per-finding risk scoring with rule-based engine (\`server/src/risk.js\`)
- Sanctioning workflow: approved / restricted / blocked / unknown
- Shadow AI report (anything detected that isn't approved)

## Pillar 3: DLP

- Browser extension watches AI prompt inputs on 10+ AI services.
- Pattern catalog: API keys (OpenAI, Anthropic, Google, GitHub PATs, AWS keys, etc.),
  PII (SSN, Luhn-validated credit cards, IBAN), CloudFuze-internal markers.
- Metadata-only reporting — never the prompt content.

## Install

See \`docs/DEPLOYMENT.md\` and \`docs/ALPHA_RUNBOOK.md\`.

## Verifying artifacts

\`\`\`
sha256sum -c SHA256SUMS.txt
\`\`\`
`;
  await writeFile(join(distRoot, 'RELEASE_NOTES.md'), body);
}

// ---- helpers ----

async function copyDir(src, dest) {
  await mkdir(dest, { recursive: true });
  const entries = await readdir(src, { withFileTypes: true });
  for (const e of entries) {
    const s = join(src, e.name);
    const d = join(dest, e.name);
    if (e.isDirectory()) await copyDir(s, d);
    else await copyFile(s, d);
  }
}

async function walkFiles(dir) {
  const out = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...await walkFiles(p));
    else out.push(p);
  }
  return out;
}

async function zipDir(srcDir, outZip, excludes = []) {
  // Use PowerShell on Windows, zip elsewhere — both are universally available.
  const excludeArgs = excludes.map((e) => `-x "${e}/*"`).join(' ');
  if (process.platform === 'win32') {
    // Build a temp staging folder to apply excludes (Compress-Archive has no exclude flag)
    const staging = outZip + '.staging';
    await rm(staging, { recursive: true, force: true });
    await copyDir(srcDir, staging);
    for (const ex of excludes) {
      await rm(join(staging, ex), { recursive: true, force: true });
    }
    await execAsync(
      `powershell -Command "Compress-Archive -Path '${staging}\\*' -DestinationPath '${outZip}' -Force"`
    );
    await rm(staging, { recursive: true, force: true });
  } else {
    await execAsync(`cd "${srcDir}" && zip -r "${outZip}" . ${excludeArgs}`);
  }
}
